name: grit
description: A simple dart program that transforms qBittorrent torrents/info API calls into NZBGet status and listgroups responses.
version: 1.0.0

environment:
  sdk: ^3.1.3

dependencies:
  args: ^2.3.0
  shelf: ^1.4.0
  shelf_plus: ^1.7.0
  shelf_router: ^1.1.0
  http: ^0.13.0


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
